CREATE TABLE E_COMMERCE (ID INT IDENTITY(1001,1), NAME VARCHAR, CATEGORY VARCHAR, DESCRIPTION VARCHAR, QUANTITY INT,CREATED_DATE DATE, LAST_MODIFIED_DATE DATE, PRIMARY KEY (ID));

INSERT INTO E_COMMERCE (NAME, CATEGORY, DESCRIPTION, QUANTITY) VALUES ('Dell 5401','Laptop', 'Dell Description', 12);
INSERT INTO  E_COMMERCE (NAME, CATEGORY, DESCRIPTION, QUANTITY) VALUES ('Dell U2413','Monitor', 'Dell Monitor', 15);
INSERT INTO  E_COMMERCE (NAME, CATEGORY, DESCRIPTION, QUANTITY) VALUES ('Samsung','Monitor', 'Samsung Monitor', 9);

